doctrine_migrations:
  name: 'SuiteCRM Migrations'
  dir_name: '%kernel.project_dir%/core/src/Migrations'
  namespace: App\Migrations
  table_name: 'migration_versions'
  column_name: 'version'
  column_length: 14
  executed_at_column_name: 'executed_at'
  organize_migrations: false
  custom_template: ~
  all_or_nothing: false
