services:
  suitecrm:
    image: "bitnami/suitecrm:latest"
    ports:
      - '8080:8080'
      - '443:443'
    volumes: 
      - 'suitecrm_data:/bitnami/suitecrm'
      - './public/legacy/modules:/bitnami/suitecrm/public/legacy/modules'
      - './public/legacy/custom/Extension/application/Ext:/bitnami/suitecrm/public/legacy/custom/Extension/application/Ext'
      #- './public/legacy/custom/Extension/modules/AOS_Products/Ext:/bitnami/suitecrm/public/legacy/custom/Extension/modules/AOS_Products/Ext' # dodatkowa definicja Vardef i Etykiet do modułu corowego  
      #- './public/legacy/custom/modules/AOS_Products/metadata:/bitnami/suitecrm/public/legacy/custom/modules/AOS_Products/metadata' # dodatkowa definicja pólwidoków do modułu corowego       
      - './public/legacy/include:/bitnami/suitecrm/public/legacy/include'
      - './public/legacy/Api:/bitnami/suitecrm/public/legacy/Api'
      - './extensions:/bitnami/suitecrm/extensions'
      - './core:/bitnami/suitecrm/core'

    environment:
      - 'SUITECRM_DATABASE_HOST=db'
      - 'SUITECRM_DATABASE_PORT_NUMBER=3306'
      - 'SUITECRM_DATABASE_USER=bn_suitecrm'
      - 'SUITECRM_DATABASE_PASSWORD=bitnami'
      - 'SUITECRM_DATABASE_NAME=bitnami_suitecrm'
    depends_on:
      - db

  db:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306:3306'  
    environment:
      - 'MARIADB_ROOT_PASSWORD=bitnami'
      - 'MARIADB_DATABASE=bitnami_suitecrm'
      - 'MARIADB_USER=bn_suitecrm'
      - 'MARIADB_PASSWORD=bitnami'
    volumes:
      - 'db_data:/bitnami/mariadb'

volumes:
  db_data:
    driver: local
  suitecrm_data:
    driver: local