SuiteCRM\Core\Modules\Users\Entity\OAuthClient:
  type: entity
  table: oauth_client
  repositoryClass: SuiteCRM\Core\Modules\Users\Storage\OAuthClientStorage
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    client_identifier:
      type: string
      max_length: 50
      unique: true
    client_secret:
      type: string
      max_length: 20
      default: ""
    redirect_uri:
      type: string
      max_length: 255
      default: ""