SuiteCRM\Core\Modules\Users\Entity\OAuthPublicKey:
  type: entity
  table: oauth_public_key
  repositoryClass:  SuiteCRM\Core\Modules\Users\Storage\OAuthPublicKeyStorage
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    public_key:
      type: string
      length: 2000
    private_key:
      type: string
      length: 2000
  manyToOne:
    client:
      targetEntity: SuiteCRM\Core\Modules\Users\Entity\OAuthClient
      joinColumn:
        name: client_id
        referencedColumnName: id
