SuiteCRM\Core\Modules\Users\Entity\OAuthUserClaims:
  type:             entity
  table:            oauth_user_claims
  repositoryClass:  SuiteCRM\Core\Modules\Users\Storage\OAuthUserClaimsStorage
  id:
    id:
      type:   integer
      generator:
        strategy: AUTO
  manyToOne:
    user:
      targetEntity: SuiteCRM\Core\Modules\Users\Entity\OAuthUser
      joinColumn:
        name:                 user_id
        referencedColumnName: id
