SuiteCRM\Core\Modules\Users\Entity\OAuthAccessToken:
  type:             entity
  table:            oauth_access_tokens
  repositoryClass:  SuiteCRM\Core\Modules\Users\Storage\OAuthAccessTokenStorage
  id:
    id:
      type:   integer
      generator:
        strategy: AUTO
  fields:
    token:
      type:       string
      max_length: 40
      unique:     true
    client_id:
      type:       integer
    user_id:
      type:       integer
      nullable:   true
    expires:
      type:       datetime
      #columnDefinition: TIMESTAMP
    scope:
      type:       string
      max_length: 50
      nullable:   true
  manyToOne:
    client:
      targetEntity: SuiteCRM\Core\Modules\Users\Entity\OAuthClient
      joinColumn:
        name:                 client_id
        referencedColumnName: id
    user:
      targetEntity: SuiteCRM\Core\Modules\Users\Entity\OAuthUser
      joinColumn:
        name:                 user_id
        referencedColumnName: id
