framework:
  secret: "%secret%"

parameters:
  secret: '%env(APP_SECRET)%'
  legacy.dir: '%kernel.project_dir%/public/legacy'
  legacy.path: '/legacy'
  legacy.session_name: 'LEGACYSESSID'
  default_session_name: 'PHPSESSID'

imports:
  - { resource: services/**/*.yaml }
  - { resource: modules/**/*.yaml }
  - { resource: modules/**/*.php }
  - { resource: core_services.yaml }
  - { resource: ../extensions/ }
