framework:
  secret: "%secret%"

parameters:
  secret: ThisTokenIsNotSoSecretChangeIt
  legacy.dir: '%kernel.project_dir%/legacy'
  legacy.session_name: 'LEGACYSESSID'
  default_session_name: 'PHPSESSID'

imports:
  - { resource: services/*/*.yaml }

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $projectDir: '%kernel.project_dir%'
      $legacyDir: '%legacy.dir%'
      $legacySessionName: '%legacy.session_name%'
      $defaultSessionName: '%default_session_name%'
      $exposedSystemConfigs: '%legacy.exposed_system_configs%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../core/src/*'
    exclude: '../core/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # makes classes in legacy/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  SuiteCRM\Core\Legacy\:
    resource: '../core/legacy/*'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../core/src/Controller/*'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\EventListener\LegacyRedirectListener:
    # set priority of 2050 to ensure the be the first running
    tags: [{ name: kernel.event_listener, event: kernel.request, priority: 2050 }]

  App\Service\ModuleNameMapper:
    arguments:
      - '%legacy.module_name_map%'

  App\Service\RouteConverter:
    arguments:
      - '@App\Service\ModuleNameMapper'
      - '%legacy.action_name_map%'
