framework:
  secret: "%secret%"

parameters:
  secret: ThisTokenIsNotSoSecretChangeIt
  legacy.dir: '%kernel.project_dir%/legacy'
  legacy.path: '/legacy'
  legacy.session_name: 'LEGACYSESSID'
  default_session_name: 'PHPSESSID'

imports:
  - { resource: services/**/*.yaml }

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $projectDir: '%kernel.project_dir%'
      $legacyDir: '%legacy.dir%'
      $legacyPath: '%legacy.path%'
      $legacySessionName: '%legacy.session_name%'
      $defaultSessionName: '%default_session_name%'
      $exposedSystemConfigs: '%legacy.exposed_system_configs%'
      $systemConfigKeyMap: '%legacy.system_config_key_map%'
      $menuItemMap: '%legacy.menu_item_map%'
      $legacyAssetPaths: '%legacy.asset_paths%'
      $legacyApiPaths: '%legacy.api_paths%'
      $exposedUserPreferences: '%legacy.exposed_user_preferences%'
      $userPreferencesKeyMap: '%legacy.user_preferences_key_map%'
      $themeImagePaths: '%themes.image_paths%'
      $themeImageSupportedTypes: '%themes.image_supported_types%'
      $frontendExcludedModules: '%legacy.frontend_excluded_modules%'
      $datetimeFormatMap: '%legacy.datetime_format_map%'
      $filterOperatorMap: '%legacy.filter_operator_map%'
      $cacheResetActions: '%legacy.cache_reset_actions%'
      $navigationTabLimits: '%themes.navigation_tab_limits%'
      $listViewBulkActions: '%module.listview.bulk_action%'
      $listViewLineActions: '%module.listview.line_action%'
      $listViewAvailableCharts: '%module.listview.available_charts%'
      $listViewColumnLimits: '%module.listview.column_limits%'
      $listViewSettingsLimits: '%module.listview.settings_limits%'
      $listViewActionsLimits: '%module.listview.actions_limits%'
  _instanceof:
    App\Service\ProcessHandlerInterface:
      tags: ['app.process.handler']
    SuiteCRM\Core\Legacy\UserPreferences\UserPreferencesMapperInterface:
      tags: ['user.preferences.mapper']
    SuiteCRM\Core\Legacy\SystemConfig\SystemConfigMapperInterface:
      tags: ['system.config.mapper']

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../core/src/*'
    exclude: '../core/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # makes classes in legacy/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  SuiteCRM\Core\Legacy\:
    resource: '../core/legacy/*'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../core/src/Controller/*'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\EventListener\LegacyRedirectListener:
    # set priority of 2050 to ensure the be the first running
    tags: [{ name: kernel.event_listener, event: kernel.request, priority: 2050 }]

  App\Service\ProcessHandlerRegistry:
    # inject all services tagged with app.process.handler as first argument
    # and use the value of the 'getProcessType' method to index the services
    arguments:
      - !tagged { tag: 'app.process.handler', default_index_method: 'getProcessType' }

  App\Security\LegacySessionDenyAccessListener:
    decorates: 'api_platform.security.listener.request.deny_access'

  App\Security\LegacySessionSecurityStage:
    decorates: 'api_platform.graphql.resolver.stage.security'

  App\Security\LegacySessionLogoutHandler:
    decorates: 'security.logout.handler.session'

  SuiteCRM\Core\Legacy\UserPreferences\UserPreferencesMappers:
    # inject all services tagged with user.preferences.mapper as first argument
    # and use the value of the 'getKey' method to index the services
    arguments:
      - !tagged { tag: 'user.preferences.mapper', default_index_method: 'getKey' }

  SuiteCRM\Core\Legacy\SystemConfig\SystemConfigMappers:
    # inject all services tagged with system.config.mapper as first argument
    # and use the value of the 'getKey' method to index the services
    arguments:
      - !tagged { tag: 'system.config.mapper', default_index_method: 'getKey' }
