parameters:
  module.recordview.actions:
    default:
      actions:
        create:
          key: create
          labelKey: LBL_NEW
          params:
            expanded: true
          modes:
            - detail
          acl:
            - edit
        edit:
          key: edit
          labelKey: LBL_EDIT
          params:
            expanded: true
          modes:
            - detail
          acl:
            - edit
        save:
          key: save
          labelKey: LBL_SAVE_BUTTON_LABEL
          params:
            expanded: true
          modes:
            - edit
          acl:
            - edit
        saveNew:
          key: saveNew
          labelKey: LBL_SAVE_BUTTON_LABEL
          params:
            expanded: true
          modes:
            - create
          acl:
            - edit
        delete:
          key: delete
          labelKey: LBL_DELETE
          asyncProcess: true
          params:
            displayConfirmation: true
            confirmationLabel: NTC_DELETE_CONFIRMATION
          modes:
            - detail
          acl:
            - delete
        duplicate:
          key: duplicate
          labelKey: LBL_DUPLICATE_BUTTON
          asyncProcess: true
          params:
          modes:
            - detail
          acl:
            - export
        audit:
          key: audit
          labelKey: LNK_VIEW_CHANGE_LOG
          asyncProcess: true
          params:
          modes:
            - detail
            - edit
          acl:
            - audit
    modules:
      employees:
        exclude:
          - delete
