parameters:
    legacy.action_name_map:
        index: index
        multieditview: multieditview
        detailview: detail
        editview: edit
        listview: list
        popup: popup
        vcard: vcard
        importvcard: importvcard
        modulelistmenu: modulelistmenu
        favorites: favorites
        noaccess: noaccess
        step1: step1
        composeview: compose
        wizardhome: wizard-home
        campaigndiagnostic: diagnostic
        webtoleadcreation: web-to-lead
        resourcelist: resource-list
        quick_radius: quick-radius

