parameters:
  legacy.asset_paths:
    - cache
    - include
    - themes
    - custom
    - vendor/tinymce
    - modules
  legacy.copy_asset_paths:
    vendor/tinymce/tinymce: 'vendor/tinymce/tinymce'
