parameters:
    legacy.exposed_system_configs:
        default_language: true
        passwordsetting:
            forgotpasswordON: true
        languages: true
        default_module: true
        default_theme: true
        module_name_map: true
        action_name_map: true
        classicview_routing_exclusions: true
        default_decimal_seperator: true
        default_number_grouping_seperator: true
        default_currency_significant_digits: true
        datef: true
        timef: true
