parameters:
  module.listview.bulk_action:
    default:
      actions:
        delete:
          key: delete
          labelKey: LBL_DELETE
          params:
            min: 1
            displayConfirmation: true
            confirmationLabel: NTC_DELETE_CONFIRMATION_MULTIPLE
          acl:
            - delete
        export:
          key: export
          labelKey: LBL_EXPORT
          params:
            min: 1
          acl:
            - export
        merge:
          key: merge
          labelKey: LBL_MERGE_DUPLICATES
          params:
            min: 2
            max: 5
          acl:
            - edit
            - delete
        massupdate:
          key: massupdate
          labelKey: LBL_MASS_UPDATE
          params:
            min: 1
            max: 5
          acl:
            - massupdate
          availability:
            - acls
            - massupdate
    modules:
      employees:
        exclude:
          - delete
          - merge
