parameters:
  module.listview.available_charts:
    modules:
      accounts:
        key: account_types_per_month
        labelKey: ACCOUNT_TYPES_PER_MONTH
        type: line
      opportunities:
        key: pipeline_by_sales_state
        labelKey: PIPELINE_BY_SALES_STAGE
        type: bar
      leads:
        key: leads_by_status
        labelKey: LEADS_BY_STATUS
        type: pie-grid
