parameters:
  module.listview.line_action:
    default:
      actions:
        create:
          key: create
          related_modules:
            calls:
              name : create-calls
              module : calls
              icon: phone
              labelKey: LBL_SCHEDULE_CALL
              returnAction: DetailView
            meetings:
              name : create-meetings
              module: meetings
              icon: calendar
              labelKey: LBL_SCHEDULE_MEETING
              returnAction: DetailView
            tasks:
              name : create-tasks
              module: tasks
              icon: list
              labelKey: LBL_CREATE_TASK
              returnAction: DetailView
            emails:
              name : create-emails
              module: emails
              icon: email
              action: compose
              labelKey: LBL_COMPOSE_EMAIL_BUTTON_LABEL
              returnAction: index
          acl:
            - edit
